### PR TITLE
Switch to using itty-router in the worker template

### PR DESCRIPTION
**Pull request by jb3**
This PR switches the template away from using a custom made worker (currently defined in router.js) and instead uses the [`itty-router`](https://github.com/kwhitley/itty-router) router to reduce complexities with routing. It removes `router.js` and adds `itty-router` to the dependencies defined in package.json.

There are a number of routes available to demonstrate different routing techniques, such as path fragments, fetching headers and more.

There is an example of this template currently running at https://router.jb3.workers.dev/, feel free to play with it!

## GET `/`

An index page, very simple.

## GET `/example/:text`

Returns a base64 encoding of provided text, useful for demonstrating path fragments and taking user input from URLs.

## POST `/post`

With no body, returns the ASN and colo of the incoming request.

When provided with a JSON body it will additionally return that data as well.

## Fallback

There is a fallback provided to show how to implement a custom 404 page and avoid raising worker exceptions.

### CODE REVIEW

**Review by signalnerve — APPROVED** [review]

**Comment by signalnerve** [comment]
This is so awesome!! I would love to get this merged but I want to share it with the Workers team first and give them a heads-up that this is planned.

cc @kwhitley as this is relevant to him too :)

**Comment by evanderkoogh** [comment]
Fine @signalnerve.. I'll throw away at least the *hour* I spend on fixing up the router one and porting it to Typescript 🗡️ 
We should make the change over at the Typescript template as well then..

**Comment by kwhitley** [comment]
Awww, I feel the love, fellas - thanks!! Just a heads up, I'm planning on adding a few super-lightweight utility functions (e.g. `asJSON(content: object): Response`) and middleware that might help abbreviate some of the boilerplate even further (if you like).  I'll be gathering up the most-essential of these little building blocks and releasing them in a tree-shakable path on `itty-router/extras` or something.

Also quick side note, I def recommend the pattern that @signalnerve used on the Cloudflare Pages tutorial with a final:
```js
router.all('*', () => new Response("Not found", { status: 404 }))
```

Especially with mixed-method routing (e.g. GET + POST), you want to catch any of those missing routes rather than failing to respond (result: Cloudflare Error page)!

Let me know if you guys catch any issues with the router or can see any room for improvement/clarification on the README.  A full docs site with much more elaborate examples will follow (e.g. making feature-rich routers *around* itty), and I'll be sure to point back to all these docs.

Also... if you guys can, you know... get me approved for the Durable Objects beta, I'm dying to start writing tooling around those!  😉 🙏

**Comment by jb3** [comment]
Hey Kevin, nice to meet you, great work on itty-router! 😄

Love the idea of the the utility functions, I'll be happy to add those here once introduced.

There is already a fallback `router.all` on line 74 with that syntax 👍. See https://router.jb3.workers.dev/notreal.

From someone who hasn't used routing before with Workers the router docs were great, very simple to pick up.

Also looking forward to Durable Objects here 😄

**Comment by kwhitley** [comment]
Not sure what the status is here, but I've been playing with Durable Objects and can confirm itty plays beautifully with it.  Have added the ES6 module syntax (required for Durable according to the docs) example to the docs:

https://www.npmjs.com/package/itty-router#cf-es6-module-syntax

Also, I've been playing with abstracting the DO implementation for a cleaner flow, and itty comes in handy there too... I may publish the abstraction class with a little less magic (obv under a more suitable name) that allows this simplicity, but overall it ends up being a pretty dang readable DO, even allowing the local methods to be used as middleware.  Internal mechanisms like persist (to storage), fetch (calls the internal router if available), and initialization (from storage) are all abstracted away:

```js
import { json, withContent } from 'itty-router-extras'

import { DurableObject } from '../class/DurableObject.js'

export class Foo extends DurableObject {
  constructor(state, env) {
    super(state, env)

    // we add routes to the embedded internal router
    this.router
      // for all requests, we increment the internal requests counter
      .all('*', this.incrementCounter)

      // a GET with '/reset' will fire the internal reset() method
      .get('/reset', this.reset)

      // PATCH to merge without wiping
      .patch('*', withContent, ({ content = {} }) => {
        Object.assign(this, content)
      })

      // POST to wipe
      .post('*', withContent, this.reset, ({ content = {} }) => {
        Object.assign(this, content)
      })

      // afterwards we persist changes, then respond with "this" as JSON
      .all('*', this.persist, () => json(this))
  }

  // increments internal counter by 1
  incrementCounter() {
    this.counter = (this.counter || 0) + 1
  }

  // removes internal data and sets counter to 0
  reset() {
    this.clear() // removes all internal data

    this.counter = 0
  }
}
```

**Comment by kwhitley** [comment]
🥳

**Comment by jb3** [comment]
:shipit::shipit::shipit:

**Pull request merged**
